// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAInaTXjOS8ec-jgpcrf0ru9j_JdoGVqzI',
    appId: '1:308289860021:web:f662757f8792edb790e9fc',
    messagingSenderId: '308289860021',
    projectId: 'myfolio-ecb89',
    authDomain: 'myfolio-ecb89.firebaseapp.com',
    storageBucket: 'myfolio-ecb89.appspot.com',
    measurementId: 'G-V9KHTMSCX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9cpoL12rrhJOtcJUdMSgfkBS68-oD4MA',
    appId: '1:308289860021:android:297d96330bb63e8990e9fc',
    messagingSenderId: '308289860021',
    projectId: 'myfolio-ecb89',
    storageBucket: 'myfolio-ecb89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJT4m9ucT3GsXMMJ9DFTJbpeIUJE_3jwE',
    appId: '1:308289860021:ios:4f298cb987a6499d90e9fc',
    messagingSenderId: '308289860021',
    projectId: 'myfolio-ecb89',
    storageBucket: 'myfolio-ecb89.appspot.com',
    iosClientId: '308289860021-ciq0e74sjhgp088galjb2s8kh1j2vld7.apps.googleusercontent.com',
    iosBundleId: 'com.ui.roba.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJT4m9ucT3GsXMMJ9DFTJbpeIUJE_3jwE',
    appId: '1:308289860021:ios:54e8d2a19b388c3390e9fc',
    messagingSenderId: '308289860021',
    projectId: 'myfolio-ecb89',
    storageBucket: 'myfolio-ecb89.appspot.com',
    iosClientId: '308289860021-h9esh0ic4dpd7u2rhn7f5918s1t43cb9.apps.googleusercontent.com',
    iosBundleId: 'com.roba.myfolio',
  );
}
